In [145]:
import pandas as pd
import data_clean_helper
import importlib

# importlib.reload(data_clean_helper)

## Data Clean

***Menu***

In [47]:
menu_df = pd.read_csv("raw data/Menu.csv", encoding='utf-8')

In [48]:
# Drop null columns
Menu_Empty_Cols_to_Drop = ['keywords', 'language', 'location_type'] # These 3 columns are 100% empty
menu_df = menu_df.drop(Menu_Empty_Cols_to_Drop, axis=1)

# Drop Redundant columns
Menu_duplicate_cols = ['name'] # menu.'name' column is 82% null, and mostly equal to the values in sponsor table
menu_df = menu_df.drop(Menu_duplicate_cols, axis=1)

# Apply common data clean for str columns
menu_df['sponsor'] = menu_df['sponsor'].apply(data_clean_helper.clean_str_col)
menu_df['location'] = menu_df['location'].apply(data_clean_helper.clean_str_col)
menu_df['notes'] = menu_df['notes'].apply(data_clean_helper.clean_notes) # Kept semicolon as speparator 

# Further clean string columns
sponsor_map = {
    'restaurant and/or location not given': '',
    'restaurant and/or location unknown': ''
}
menu_df['sponsor'] = menu_df['sponsor'].replace(sponsor_map)
menu_df['location'] = menu_df['location'].replace(sponsor_map)


# Covert date column to proper datetime
menu_df['date'] = pd.to_datetime(menu_df['date'], errors='coerce')
invalid_dates = menu_df[menu_df['date'].isna() & menu_df['date'].notna()]
print(f"Validation - There are {len(invalid_dates)} invalid date value found.")

Validation - There are 0 invalid date value found.

In [49]:
menu_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17545 entries, 0 to 17544
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    17545 non-null  int64
 1   sponsor               15984 non-null  object
 2   event                 8154 non-null   object
 3   venue                 8119 non-null   object
 4   place                 8123 non-null   object
 5   physical_description  14763 non-null  object
 6   occasion              3791 non-null   object
 7   notes                 10613 non-null  object
 8   call_number           15983 non-null  object
 9   date                  16954 non-null  datetime64[ns]
 10  location              17545 non-null  object
 11  currency              6456 non-null   object
 12  currency_symbol       6456 non-null   object
 13  status                17545 non-null  object
 14  page_count            17545 non-null  int64
 15  dish_count            17545 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(12)
memory usage: 2.1+ MB

In [50]:
menu_df.head()

,id,sponsor,event,venue,place,physical_description,occasion,notes,call_number,date,location,currency,currency_symbol,status,page_count,dish_count
0,12463,hotel eastman,BREAKFAST,COMMERCIAL,"HOT SPRINGS, AR",CARD; 4.75X7.5;,EASTER;,NaN,1900-2822,1900-04-15,hotel eastman,NaN,NaN,complete,2,67
1,12464,republican house,[DINNER],COMMERCIAL,"MILWAUKEE, [WI];",CARD; ILLUS; COL; 7.0X9.0;,EASTER;,wedgewood blue card; white embossed greek key ...,1900-2825,1900-04-15,republican house,NaN,NaN,under review,2,34
2,12465,norddeutscher lloyd bremen,FRUHSTUCK/BREAKFAST;,COMMERCIAL,DAMPFER KAISER WILHELM DER GROSSE;,CARD; ILLU; COL; 5.5X8.0;,NaN,menu in german and english; illus steamship an...,1900-2827,1900-04-16,norddeutscher lloyd bremen,NaN,NaN,complete,2,84
3,12466,norddeutscher lloyd bremen,LUNCH;,COMMERCIAL,DAMPFER KAISER WILHELM DER GROSSE;,CARD; ILLU; COL; 5.5X8.0;,NaN,menu in german and english; illus harbor scene...,1900-2828,1900-04-16,norddeutscher lloyd bremen,NaN,NaN,complete,2,63
4,12467,norddeutscher lloyd bremen,DINNER;,COMMERCIAL,DAMPFER KAISER WILHELM DER GROSSE;,FOLDER; ILLU; COL; 5.5X7.5;,NaN,menu in german and english; illus harbor scene...,1900-2829,1900-04-16,norddeutscher lloyd bremen,NaN,NaN,complete,4,33

***Menu Page***

In [137]:
menuPage_df = pd.read_csv("raw data/MenuPage.csv", encoding='utf-8')

In [138]:
# Ensure the column is numeric
menuPage_df['page_number'] = pd.to_numeric(menuPage_df['page_number'], errors='coerce')
# Count how many values are not integer-like
non_integer_count = menuPage_df['page_number'].dropna().apply(lambda x: x % 1 != 0).sum()
print(f"Validation - page_number column - There are {non_integer_count} values found as not integer (exclude NaN).")

menuPage_df['page_number'] = menuPage_df['page_number'].astype('Int64')
print(f"Clean - page_number column - Converted dtype to int.")

Validation - page_number column - There are 0 values found as not integer (exclude NaN).
Clean - page_number column - Converted dtype to int.

In [139]:
menuPage_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66937 entries, 0 to 66936
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           66937 non-null  int64
 1   menu_id      66937 non-null  int64
 2   page_number  65735 non-null  Int64
 3   image_id     66937 non-null  object
 4   full_height  66608 non-null  float64
 5   full_width   66608 non-null  float64
 6   uuid         66937 non-null  object
dtypes: Int64(1), float64(2), int64(2), object(2)
memory usage: 3.6+ MB

In [140]:
menuPage_df.head()

,id,menu_id,page_number,image_id,full_height,full_width,uuid
0,119,12460,1,1603595,7230.0,5428.0,510d47e4-2955-a3d9-e040-e00a18064a99
1,120,12460,2,1603596,5428.0,7230.0,510d47e4-2956-a3d9-e040-e00a18064a99
2,121,12460,3,1603597,7230.0,5428.0,510d47e4-2957-a3d9-e040-e00a18064a99
3,122,12460,4,1603598,7230.0,5428.0,510d47e4-2958-a3d9-e040-e00a18064a99
4,123,12461,1,1603591,7230.0,5428.0,510d47e4-2959-a3d9-e040-e00a18064a99

***Menu Item***

In [70]:
menuItem_df = pd.read_csv("raw data/MenuItem.csv", encoding='utf-8')

In [71]:
# Apply the check
menuItem_df['not_utc'] = menuItem_df['created_at'].apply(
    lambda x: isinstance(x, str) and 'utc' not in x.lower()
)
non_utc_rows = menuItem_df[menuItem_df['not_utc']]
print(f"Validation - There are {len(non_utc_rows)} rows from created_at column found as not UTC timezone")

menuItem_df['not_utc'] = menuItem_df['updated_at'].apply(
    lambda x: isinstance(x, str) and 'utc' not in x.lower()
)
non_utc_rows = menuItem_df[menuItem_df['not_utc']]
print(f"Validation - There are {len(non_utc_rows)} rows from updated_at column found as not UTC timezone")
menuItem_df = menuItem_df.drop(columns = ['not_utc'])

# Convert both timestamp column to date
menuItem_df['created_at'] = pd.to_datetime(menuItem_df['created_at'], utc=True).dt.date
menuItem_df['updated_at'] = pd.to_datetime(menuItem_df['updated_at'], utc=True).dt.date
print(f"\nClean - Coverted two timestamps column to date.")

Validation - There are 0 rows from created_at column found as not UTC timezone
Validation - There are 0 rows from updated_at column found as not UTC timezone

Clean - Coverted two timestamps column to date.

In [73]:
# Ensure the column is numeric
menuItem_df['dish_id'] = pd.to_numeric(menuItem_df['dish_id'], errors='coerce')
# Count how many values are not integer-like
non_integer_count = menuItem_df['dish_id'].dropna().apply(lambda x: x % 1 != 0).sum()
print(f"Validation - dish_id column - There are {non_integer_count} values found as not integer(exclude NaN).")

menuItem_df['dish_id'] = menuItem_df['dish_id'].astype('Int64')
print(f"Clean - page_number column - Converted dtype to int.")

Validation - dish_id column - There are 0 values found as not integer(exclude NaN).
Clean - page_number column - Converted dtype to int.

In [74]:
menuItem_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1332726 entries, 0 to 1332725
Data columns (total 9 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   id            1332726 non-null  int64
 1   menu_page_id  1332726 non-null  int64
 2   price         886810 non-null   float64
 3   high_price    91905 non-null    float64
 4   dish_id       1332485 non-null  Int64
 5   created_at    1332726 non-null  object
 6   updated_at    1332726 non-null  object
 7   xpos          1332726 non-null  float64
 8   ypos          1332726 non-null  float64
dtypes: Int64(1), float64(4), int64(2), object(2)
memory usage: 92.8+ MB

In [75]:
menuItem_df.head()

,id,menu_page_id,price,high_price,dish_id,created_at,updated_at,xpos,ypos
0,1,1389,0.4,NaN,1,2011-03-28,2011-04-19,0.111429,0.254735
1,2,1389,0.6,NaN,2,2011-03-28,2011-04-19,0.438571,0.254735
2,3,1389,0.4,NaN,3,2011-03-28,2011-04-19,0.140000,0.261922
3,4,1389,0.5,NaN,4,2011-03-28,2011-04-19,0.377143,0.262720
4,5,3079,0.5,1.0,5,2011-03-28,2011-04-13,0.105714,0.313178

***Dish***

In [125]:
dish_df = pd.read_csv("raw data/dish.csv", encoding='utf-8')

In [126]:
# Drop null columns
dish_Empty_Cols_to_Drop = ['description'] # this column is 100% empty
dish_df = dish_df.drop(dish_Empty_Cols_to_Drop, axis=1)

# Apply common data clean for str columns
dish_df['name'] = dish_df['name'].apply(data_clean_helper.clean_str_col)

In [127]:
print(f"Validation - There are {dish_df.id.nunique()} unique dish id found in this table - means no duplicate id")

Validation - There are 423397 unique dish id found in this table - means no duplicate id

In [128]:
dish_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 423397 entries, 0 to 423396
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              423397 non-null  int64
 1   name            423397 non-null  object
 2   menus_appeared  423397 non-null  int64
 3   times_appeared  423397 non-null  int64
 4   first_appeared  423397 non-null  int64
 5   last_appeared   423397 non-null  int64
 6   lowest_price    394297 non-null  float64
 7   highest_price   394297 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 25.8+ MB

In [129]:
dish_df.head()

,id,name,menus_appeared,times_appeared,first_appeared,last_appeared,lowest_price,highest_price
0,1,consomme printaniere royal,8,8,1897,1927,0.20,0.4
1,2,chicken gumbo,111,117,1895,1960,0.10,0.8
2,3,tomato aux croutons,13,13,1893,1917,0.25,0.4
3,4,onion au gratin,41,41,1900,1971,0.25,1.0
4,5,st emilion,66,68,1881,1981,0.00,18.0

In [130]:
# dish_df.name.sort_values().to_csv('output.txt', index=False, header=False)

### Validation: Merge datasets by IDs

In [142]:
# Both Dish and menuItem table contains dish id
dish_df = dish_df.rename(columns = {'id': 'dish_id'})
menuItem_df = menuItem_df.rename(columns = {'id': 'menuItem_id'})

# - First check the coverage
unique_dishid_in_dish = set(dish_df['dish_id']) - set(menuItem_df['dish_id'])

print(f"There are {len(unique_dishid_in_dish)} unique dishes don't have a match in menuItem table.")
print(f"- which is {(round(len(unique_dishid_in_dish)/len(dish_df) * 100))}% of dishes in dish table.")

There are 9262 unique dishes don't have a match in menuItem table.
- which is 2% of dishes in dish table.

In [143]:
# Both menuItem and menuPage table contains menu_page_id
menuPage_df = menuPage_df.rename(columns = {'id': 'menu_page_id'})

# - First check the coverage
unique_menuPage_in_menuItem = set(menuItem_df['menu_page_id'].unique()) - set(menuPage_df['menu_page_id'])

print(f"There are {len(unique_menuPage_in_menuItem)} unique menu items don't have a match in menuPage table.")
print(f"- which is {(round(len(unique_menuPage_in_menuItem)/len(menuItem_df) * 100))}% of menuItem in menu Item table.")

There are 0 unique menu items don't have a match in menuPage table.
- which is 0% of menuItem in menu Item table.

In [144]:
# Both menuPage and menu table contains menu_id
menu_df = menu_df.rename(columns = {'id': 'menu_id'})

# - First check the coverage
unique_menu_in_menuPage = set(menuPage_df['menu_id']) - set(menu_df['menu_id'])

print(f"There are {len(unique_menu_in_menuPage)} unique menu items don't have a match in menuPage table.")
print(f"- which is {(round(len(unique_menu_in_menuPage)/len(menuPage_df) * 100))}% of menu in menu Item table.")

There are 2271 unique menu items don't have a match in menuPage table.
- which is 3% of menu in menu Item table.